name: Animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  Generate-Snake-Game:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
