name: Animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  Generate-Snake-Game:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Contents will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
